### ISSUE TITLE
Proxy support for test-kitchen (vagrant adapter)

### ISSUE THREAD

**Issue by jperville** [tmatilai/vagrant-proxyconf#64]
Hello @tmatilai,

It took me a while to understand how to configure chef running in `test-kitchen` to use my proxy settings. Unlike in #21 there is no special provisioner that can be detected in `config.vm.provisioners` then configured.

After reading test-kitchen/kitchen-vagrant#90 and especially @esciara's comments, I ended up putting the following content in my `~/.kitchen/config.yml`.

``` yaml

---
provisioner:
  solo_rb:
    http_proxy: http://10.0.3.84:3128
    https_proxy: http://10.0.3.84:3128
    no_proxy: localhost,127.0.0.1
  client_rb:
    http_proxy: http://10.0.3.84:3128
    https_proxy: http://10.0.3.84:3128
    no_proxy: localhost,127.0.0.1
```

This should work with both the chef_zero and chef_solo provisioners that are used under the hood by the vagrant adapter for test-kitchen.

It would be nice to have `vagrant-proxyconf` detect when it is running through kitchen-vagrant (test-kitchen's vagrant adapter) and fill these attributes automatically.
